// <auto-generated />
using CRUD_Operations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRUD_Operations.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CRUD_Operations.CardModel", b =>
                {
                    b.Property<int>("cardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cardId"), 1L, 1);

                    b.Property<string>("card_Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Card Name");

                    b.Property<string>("imagePath")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Image Path");

                    b.Property<int>("price")
                        .HasColumnType("int")
                        .HasColumnName("Price");

                    b.HasKey("cardId");

                    b.ToTable("CardTable");
                });
#pragma warning restore 612, 618
        }
    }
}
